version: '3.9'

services:
  db:
    image: postgres:16.11
    container_name: beauty_center_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-beauty_center}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-gezgez}

    ports:
      - "5432:5432"

    volumes:
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
    driver: local
