version: '3.8'
services:
  db:
    image: postgres:16.11
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-beauty_center_db}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-mouadhmb12}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped
volumes:
  db_data:
