spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  defer-datasource-initialization: false
  security:
    user:
      name: ""
      password: ""

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

jwt:
  secret: ${JWT_SECRET}
encryption:
  key: ${ENCRYPTION_KEY}

logging:
  level:
    root: WARN
    beauty_center: INFO
    org.springframework: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.flywaydb: INFO
